### ISSUE TITLE
Beta to test!

### ISSUE THREAD

**Issue by stefangal** [stefangal/Minesweeper#1]
Please help me to test. Good for beginners for learning.

**Comment by someonewho** [comment]
Hi, I'm interested in your project. So, I want to contribute to the test. What items do you want to test?

**Comment by stefangal** [comment]
@someonewho Hi. Thanks for your help in advance. Would be good to test the game itself so it doesn't throw any error.

**Comment by someonewho** [comment]
I think game needs restart button and pause button. I know that your game has restart button, but sadly it doesn't work.
